### ISSUE TITLE
How to deploy it behind Traefik

### ISSUE THREAD

**Issue by MADx00** [MISP/misp-docker#12]
Hi team,

I am facing some issues when deploying behind Traefik (reverse proxy), even though I tried to route the reverse proxy (Traefik) to port 80.

my infrastructure is as follows:
- I am deploying Traefik from my main docker-compose.yml file, where I created a bridge network called "myNetwork"
- "misp-docker" is cloned, configured (.env), and deployed from other folder, but it can reach Traefik through "myNetwork"

my version of "misp-core" in docker-compose.yml is below:

```
  misp-core:
    image: ghcr.io/misp/misp-docker/misp-core:latest
    container_name: misp-core
    build:
      context: core/.
      args:
          - CORE_TAG=${CORE_TAG}
          - CORE_COMMIT=${CORE_COMMIT}
          - PHP_VER=${PHP_VER}
          - PYPI_REDIS_VERSION=${PYPI_REDIS_VERSION}
          - PYPI_LIEF_VERSION=${PYPI_LIEF_VERSION}
          - PYPI_PYDEEP2_VERSION=${PYPI_PYDEEP2_VERSION}
          - PYPI_PYTHON_MAGIC_VERSION=${PYPI_PYTHON_MAGIC_VERSION}
          - PYPI_MISP_LIB_STIX2_VERSION=${PYPI_MISP_LIB_STIX2_VERSION}
          - PYPI_MAEC_VERSION=${PYPI_MAEC_VERSION}
          - PYPI_MIXBOX_VERSION=${PYPI_MIXBOX_VERSION}
          - PYPI_CYBOX_VERSION=${PYPI_CYBOX_VERSION}
          - PYPI_PYMISP_VERSION=${PYPI_PYMISP_VERSION}
    depends_on:
      - redis
      - db
    #ports:
    #  - "80:80"
    #  - "443:443"
    volumes:
      - "./config-configs/:/var/www/MISP/app/Config/"
      - "./config-logs/:/var/www/MISP/app/tmp/logs/"
      - "./config-files/:/var/www/MISP/app/files/"
      - "./config-ssl/:/etc/nginx/certs/"
      - "./config-gnupg/:/var/www/MISP/.gnupg/"
      # customize by replacing ${CUSTOM_PATH} with a path containing 'files/customize_misp.sh'
      # - "${CUSTOM_PATH}/:/custom/"
    environment:
      - "BASE_URL=${BASE_URL}"
      - "CRON_USER_ID=${CRON_USER_ID}"
      - "DISABLE_IPV6=${DISABLE_IPV6}"
      # standard settings
      - "ADMIN_EMAIL=${ADMIN_EMAIL}"
      - "ADMIN_PASSWORD=${ADMIN_PASSWORD}"
      - "ADMIN_KEY=${ADMIN_KEY}"
      - "ADMIN_ORG=${ADMIN_ORG}"
      - "GPG_PASSPHRASE=${GPG_PASSPHRASE}"
      # authentication settings
      #- "OIDC_ENABLE=${OIDC_ENABLE}"
      #- "OIDC_PROVIDER_URL=${OIDC_PROVIDER_URL}"
      #- "OIDC_CLIENT_ID=${OIDC_CLIENT_ID}"
      #- "OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}"
      #- "OIDC_ROLES_PROPERTY=${OIDC_ROLES_PROPERTY}"
      #- "OIDC_ROLES_MAPPING=${OIDC_ROLES_MAPPING}"
      #- "OIDC_DEFAULT_ORG=${OIDC_DEFAULT_ORG}"
      # sync server settings (see https://www.misp-project.org/openapi/#tag/Servers for more options)
      - "SYNCSERVERS=${SYNCSERVERS}"
      - |
        SYNCSERVERS_1_DATA=
        {
          "remote_org_uuid": "${SYNCSERVERS_1_UUID}",
          "name": "${SYNCSERVERS_1_NAME}",
          "authkey": "${SYNCSERVERS_1_KEY}",
          "url": "${SYNCSERVERS_1_URL}",
          "pull": true
        }
      # mysql settings
      - "MYSQL_HOST=${MYSQL_HOST:-db}"
      - "MYSQL_PORT=${MYSQL_PORT:-3306}"
      - "MYSQL_USER=${MYSQL_USER:-misp}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-example}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE:-misp}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.misp.rule=Host(`misp.mydomain.net`)"
      - "traefik.http.routers.misp.entrypoints=websecure"
      - "traefik.http.services.misp.loadbalancer.server.port=80"
      - "traefik.http.routers.misp.service=misp"
      - "traefik.http.routers.misp.tls=true"
      - "traefik.http.routers.misp.tls.certresolver=letsencrypt"
    networks:
      - myNetwork

```

my ".env" configuration is below:
```
##
# Build-time variables
##

CORE_TAG=v2.4.183
MODULES_TAG=v2.4.182
PHP_VER=20190902
LIBFAUP_COMMIT=3a26d0a

# PYPY_* vars take precedence over MISP's
# PYPI_REDIS_VERSION="==5.0.*"
# PYPI_LIEF_VERSION=">=0.13.1"
# PYPI_PYDEEP2_VERSION="==0.5.*"
# PYPI_PYTHON_MAGIC_VERSION="==0.4.*"
# PYPI_MISP_LIB_STIX2_VERSION="==3.0.*"
# PYPI_MAEC_VERSION="==4.1.*"
# PYPI_MIXBOX_VERSION="==1.0.*"
# PYPI_CYBOX_VERSION="==2.1.*"
# PYPI_PYMISP_VERSION="==2.4.178"

# CORE_COMMIT takes precedence over CORE_TAG
# CORE_COMMIT=c56d537
# MODULES_COMMIT takes precedence over MODULES_TAG
# MODULES_COMMIT=de69ae3

##
# Run-time variables
##

# Email/username for user #1, defaults to MISP's default (admin@admin.test)
ADMIN_EMAIL=xxxxxxxxxx@mydomain.net
# name of org #1, default to MISP's default (ORGNAME)
ADMIN_ORG=mydomain
# defaults to an automatically generated one
ADMIN_KEY=
# defaults to MISP's default (admin)
ADMIN_PASSWORD=xxxxxxxxxx
# defaults to 'passphrase'
GPG_PASSPHRASE=
# defaults to 1 (the admin user)
CRON_USER_ID=
# defaults to 'https://localhost'
BASE_URL=misp.mydomain.net

# optional and used by the mail sub-system
SMARTHOST_ADDRESS=smtp.mydomain.net
SMARTHOST_PORT=587
SMARTHOST_USER=emailapikey
SMARTHOST_PASSWORD=xxxxxxxxxx
SMARTHOST_ALIASES=misp@mydomain.net

# optional comma separated list of IDs of syncservers (e.g. SYNCSERVERS=1)
# For this to work ADMIN_KEY must be set, or AUTOGEN_ADMIN_KEY must be true (default)
SYNCSERVERS=
# note: if you have more than one syncserver, you need to update docker-compose.yml
SYNCSERVERS_1_URL=
SYNCSERVERS_1_NAME=
SYNCSERVERS_1_UUID=
SYNCSERVERS_1_KEY=

# optional and used to set mysql db and credentials
MYSQL_HOST=db
# MYSQL_PORT=
MYSQL_USER=misp
MYSQL_PASSWORD=xxxxxxxxxx
# MYSQL_ROOT_PASSWORD=
MYSQL_DATABASE=misp

# These variables allows overriding some MISP email values.
# They all default to ADMIN_EMAIL.

# MISP.email, used for notifications. Also used
# for GnuPG.email and GPG autogeneration.
# MISP_EMAIL=

# MISP.contact, the e-mail address that
# MISP should include as a contact address
# for the instance's support team.
# MISP_CONTACT=

# Enable GPG autogeneration (default true)
# AUTOCONF_GPG=true

# Enable admin (user #1) API key autogeneration
# if ADMIN_KEY is not set above (default true)
# AUTOGEN_ADMIN_KEY=true

# Disable IPv6 completely (this setting will persist until the container is removed)
# DISABLE_IPV6=true

# Enable OIDC authentication, according to https://github.com/MISP/MISP/blob/2.4/app/Plugin/OidcAuth/README.md
# OIDC_ENABLE=true
# OIDC_PROVIDER_URL=
# OIDC_CLIENT_ID=
# OIDC_CLIENT_SECRET=
# OIDC_ROLES_PROPERTY="roles"
# OIDC_ROLES_MAPPING={"admin": "1","sync-user": "5"}
# OIDC_DEFAULT_ORG=
